SET (TIPSY_SRCS 
  ${TIPSY_SOURCE_DIR}/vtkTipsyReader.cxx
  )

INCLUDE_DIRECTORIES(${TIPSY_SOURCE_DIR})
INCLUDE_DIRECTORIES(${TIPSY_SOURCE_DIR}/..)

PARAVIEW_INCLUDE_WRAPPED_SOURCES("${TIPSY_SRCS}")
PARAVIEW_INCLUDE_SERVERMANAGER_RESOURCES("${MYFANCY_SOURCE_DIR}/ServerManagerXML.xml")
PARAVIEW_INCLUDE_GUI_RESOURCES("${MYFANCY_SOURCE_DIR}/TipsyReaderGUI.xml")
